### ISSUE TITLE
ParquetReader大文件内存溢出

### ISSUE THREAD

**Issue by zmin1217** [wgzhao/DataX#132]
您的这种ParquetReader(AvroParquetReader)在读大文件(约20G)的时候会有内存溢出吗？我用过网上的一种方式类似于OrcReader（使用Serde和FileInputFormat），这种方式在读20G的parquet文件时，会内存溢出，然后不断的加大内存和降低并发线程

**Comment by wgzhao** [comment]
目前我在生产环境中未出现这种情况

**Comment by zmin1217** [comment]
你读的最大的parquet文件大概多大啊，设置了多大的内存和并发

**Comment by wgzhao** [comment]
我们生产上绝大部分都是ORC格式，Parquet我找了几个文件，都是2G左右，所以可能不具备你说的这个触发条件，如果你有这样的环境，可以尝试测试看看是否存在这个问题。

**Comment by zmin1217** [comment]
测试了一下也是有OOM
`Exception in thread "main" java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.intellij.rt.execution.CommandLineWrapper.main(CommandLineWrapper.java:63)
Caused by: java.lang.OutOfMemoryError: Java heap space
	at org.apache.parquet.bytes.BytesInput$StreamBytesInput.toByteArray(BytesInput.java:262)
	at org.apache.parquet.bytes.BytesInput.toByteBuffer(BytesInput.java:214)
	at org.apache.parquet.bytes.BytesInput.toInputStream(BytesInput.java:223)
	at org.apache.parquet.column.impl.ColumnReaderImpl.readPageV1(ColumnReaderImpl.java:592)
	at org.apache.parquet.column.impl.ColumnReaderImpl.access$300(ColumnReaderImpl.java:57)
	at org.apache.parquet.column.impl.ColumnReaderImpl$3.visit(ColumnReaderImpl.java:536)
	at org.apache.parquet.column.impl.ColumnReaderImpl$3.visit(ColumnReaderImpl.java:533)
	at org.apache.parquet.column.page.DataPageV1.accept(DataPageV1.java:95)
	at org.apache.parquet.column.impl.ColumnReaderImpl.readPage(ColumnReaderImpl.java:533)
	at org.apache.parquet.column.impl.ColumnReaderImpl.checkRead(ColumnReaderImpl.java:525)
	at org.apache.parquet.column.impl.ColumnReaderImpl.consume(ColumnReaderImpl.java:638)
	at org.apache.parquet.io.RecordReaderImplementation.read(RecordReaderImplementation.java:408)
	at org.apache.parquet.hadoop.InternalParquetRecordReader.nextKeyValue(InternalParquetRecordReader.java:226)
	at org.apache.parquet.hadoop.ParquetReader.read(ParquetReader.java:132)`

你生产环境的ORC是多大的文件啊，然后配置了多大的内存

**Comment by wgzhao** [comment]
生产环境我们特意设定不会去产生很大的单个文件，ORC文件也会限制在单个文件2G左右，所以datax配置的内存很小，最大2G。

你这个报错，尝试增大内存试试，修改 `bin/datax.py` 文件 修改 `DEFAULT_JVM` 环境变量中的 `-Xmx2g` 这个值试试

有时间我也在我生产环境测试下

**Comment by zmin1217** [comment]
我把parquet文件切成很多小文件（2G左右），单线程读其中的一个parquet文件(1.1G，数据量323844行，有437列)，设置-Xms2g -Xmx2g，读到大概13万行的时候就OOM了

**Comment by wgzhao** [comment]
我在自己环境下测试

首先测试从内存读取一亿条数据，然后以Parquet格式写入到HDFS，配置文件如下：

```json
{
    "job": {
        "setting": {
            "speed": {
                "byte": -1,
                "channel": 1
            }
        },
        "content": [
            {
                "reader": {
                    "name": "streamreader",
                    "parameter": {
                        "column": [
                            {
                                "value": "DataX",
                                "type": "string"
                            },
                            {
                                "value": 19890604,
                                "type": "long"
                            },
                            {
                                "value": "1989-06-04 00:00:00",
                                "type": "date"
                            },
                            {
                                "value": true,
                                "type": "bool"
                            },
                            {
                                "value": "test",
                                "type": "bytes"
                            }
                        ],
                        "sliceRecordCount": 100000000
                    }
                },
                "writer": {
                    "name": "hdfswriter",
                    "parameter": {
                        "path": "/tmp/out_parquet",
                        "fileName": "dx.dat",
                        "compress": "SNAPPY",
                        "column": [
                            {
                                "name": "col1",
                                "type": "string"
                            },
                            {
                                "name": "col2",
                                "type": "int"
                            },
                            {
                                "name": "col3",
                                "type": "string"
                            },
                            {
                                "name": "col4",
                                "type": "boolean"
                            },
                            {
                                "name": "col5",
                                "type": "string"
                            }
                        ],
                        "defaultFS": "hdfs://127.0.0.1:8020",
                        "writeMode": "overwrite",
                        "fieldDelimiter": "\u0001",
                        "fileType": "parquet"
                    }
                }
            }
        ]
    }
}
```

`datax.py` 设置最大内存为2g，执行结果如下：

```
2021-02-26 16:05:34.618 [job-0] INFO  StandAloneJobContainerCommunicator - 
Total 100000000 records, 2600000000 bytes | Speed 5.37MB/s, 216450 records/s | Error 0 records, 0 bytes |  All Task WaitWriterTime 454.685s |  All Task WaitReaderTime 2.103s | Percentage 100.00%
2021-02-26 16:05:34.619 [job-0] INFO  JobContainer -
任务启动时刻                    : 2021-02-26 15:57:51
任务结束时刻                    : 2021-02-26 16:05:34
任务总计耗时                    :                463s
任务平均流量                    :            5.37MB/s
记录写入速度                    :         216450rec/s
读出记录总数                    :           100000000
```
因为数据相同，所以最终写入的文件不大，只有200M。

其次，尝试读取该文件
