### ISSUE TITLE
txtfilereader 报错 java.lang.NoClassDefFoundError: org/apache/hadoop/io/compress/CompressionCodec

### ISSUE THREAD

**Issue by covered** [wgzhao/DataX#149]
```json
       "reader": {
            "name": "txtfilereader",
            "parameter": {
                "path": ["/home/go/da/*"],
                "encoding": "UTF-8",
                "skipHeader": true,
                "column": [
                    {

                    {
                        "index": 27,
                        "type": "long"
                    }
                ],
                "fieldDelimiter": ",",
                "csvReaderConfig":{
                  "safetySwitch": false,
                  "skipEmptyRecords": false,
                  "useTextQualifier": false
                }
            }
        },
```

```
2021-03-16 04:49:17.438 [main] INFO  PerfTrace - PerfTrace traceId=job_-1, isEnable=false, priority=0
2021-03-16 04:49:17.439 [main] INFO  JobContainer - DataX jobContainer starts job.
2021-03-16 04:49:17.447 [main] INFO  JobContainer - Set jobId = 0
2021-03-16 04:49:17.802 [job-0] INFO  JobContainer - PerfTrace not enable!
Exception in thread "job-0" java.lang.NoClassDefFoundError: org/apache/hadoop/io/compress/CompressionCodec
        at com.wgzhao.datax.plugin.reader.txtfilereader.TxtFileReader$Job.init(TxtFileReader.java:68)
        at com.wgzhao.datax.core.job.JobContainer.initJobReader(JobContainer.java:661)
        at com.wgzhao.datax.core.job.JobContainer.init(JobContainer.java:306)
        at com.wgzhao.datax.core.job.JobContainer.start(JobContainer.java:113)
        at com.wgzhao.datax.core.Engine.start(Engine.java:86)
        at com.wgzhao.datax.core.Engine.entry(Engine.java:146)
        at com.wgzhao.datax.core.Engine.main(Engine.java:164)
Caused by: java.lang.ClassNotFoundException: org.apache.hadoop.io.compress.CompressionCodec
        at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        ... 7 more
```

**Comment by wgzhao** [comment]
@covered 请问使用的是哪个版本？

**Comment by wgzhao** [comment]
@covered 缺乏 `hadoop-common` 包，可以执行下面的命令拷贝一个jar包过去

```shell
cp plugin/reader/hbase11xreader/libs/hadoop-common-2.7.4.jar plugin/reader/txtfilereader/libs
```
也可以下载[hadoop-common-2.7.4.jar.zip](https://github.com/wgzhao/DataX/files/6148780/hadoop-common-2.7.4.jar.zip)压缩包，然后解压缩到 `plugin/reader/txtfilereader/libs` 文件夹
