### ISSUE TITLE
org.apache.avro.AvroRuntimeException: Field xxxx type:STRING pos:3 not set and has no default value

### ISSUE THREAD

**Issue by ititdog** [wgzhao/DataX#156]
mysql   导入 hive， 如 mysql(字段name, 类型varchar, 值均为null)  导入 hive（parquet, 类型string）   报错 not set and has no default value;   这个如何解决

**Comment by wgzhao** [comment]
@ititdog 感谢反馈
可否给执行时的实际输出内容（敏感内容可以删除），这样方便快速定位问题

**Comment by wgzhao** [comment]
```
com.wgzhao.datax.common.exception.DataXException: Code:[HdfsWriter-04], Description:[您配置的文件在写入时出现IO异常.]. - org.apache.avro.AvroRuntimeException: Field name type:STRING pos:1 not set and has no default value
	at org.apache.avro.generic.GenericData.getDefaultValue(GenericData.java:1015)
	at org.apache.avro.data.RecordBuilderBase.defaultValue(RecordBuilderBase.java:138)
	at org.apache.avro.generic.GenericRecordBuilder.getWithDefault(GenericRecordBuilder.java:232)
	at org.apache.avro.generic.GenericRecordBuilder.build(GenericRecordBuilder.java:209)
	at com.wgzhao.datax.plugin.writer.hdfswriter.HdfsHelper.transportParRecord(HdfsHelper.java:269)
	at com.wgzhao.datax.plugin.writer.hdfswriter.HdfsHelper.parquetFileStartWrite(HdfsHelper.java:691)
	at com.wgzhao.datax.plugin.writer.hdfswriter.HdfsWriter$Task.startWrite(HdfsWriter.java:437)
	at com.wgzhao.datax.core.taskgroup.runner.WriterRunner.run(WriterRunner.java:81)
	at java.lang.Thread.run(Thread.java:748)
 - org.apache.avro.AvroRuntimeException: Field name type:STRING pos:1 not set and has no default value
	at org.apache.avro.generic.GenericData.getDefaultValue(GenericData.java:1015)
	at org.apache.avro.data.RecordBuilderBase.defaultValue(RecordBuilderBase.java:138)
	at org.apache.avro.generic.GenericRecordBuilder.getWithDefault(GenericRecordBuilder.java:232)
	at org.apache.avro.generic.GenericRecordBuilder.build(GenericRecordBuilder.java:209)
	at com.wgzhao.datax.plugin.writer.hdfswriter.HdfsHelper.transportParRecord(HdfsHelper.java:269)
	at com.wgzhao.datax.plugin.writer.hdfswriter.HdfsHelper.parquetFileStartWrite(HdfsHelper.java:691)
	at com.wgzhao.datax.plugin.writer.hdfswriter.HdfsWriter$Task.startWrite(HdfsWriter.java:437)
	at com.wgzhao.datax.core.taskgroup.runner.WriterRunner.run(WriterRunner.java:81)
	at java.lang.Thread.run(Thread.java:748)

	at com.wgzhao.datax.common.exception.DataXException.asDataXException(DataXException.java:66)
	at com.wgzhao.datax.plugin.writer.hdfswriter.HdfsHelper.parquetFileStartWrite(HdfsHelper.java:698)
	at com.wgzhao.datax.plugin.writer.hdfswriter.HdfsWriter$Task.startWrite(HdfsWriter.java:437)
	at com.wgzhao.datax.core.taskgroup.runner.WriterRunner.run(WriterRunner.java:81)
	at java.lang.Thread.run(Thread.java:748)
Caused by: org.apache.avro.AvroRuntimeException: Field name type:STRING pos:1 not set and has no default value
	at org.apache.avro.generic.GenericData.getDefaultValue(GenericData.java:1015)
	at org.apache.avro.data.RecordBuilderBase.defaultValue(RecordBuilderBase.java:138)
	at org.apache.avro.generic.GenericRecordBuilder.getWithDefault(GenericRecordBuilder.java:232)
	at org.apache.avro.generic.GenericRecordBuilder.build(GenericRecordBuilder.java:209)
	at com.wgzhao.datax.plugin.writer.hdfswriter.HdfsHelper.transportParRecord(HdfsHelper.java:269)
	at com.wgzhao.datax.plugin.writer.hdfswriter.HdfsHelper.parquetFileStartWrite(HdfsHelper.java:691)
	... 3 common frames omitted
```
