### ISSUE TITLE
HttpReader插件当属性值是null时，无法读取

### ISSUE THREAD

**Issue by meihuasannong** [wgzhao/DataX#171]
**Describe the bug**

**To Reproduce**
1. paste  json content of running job
2. paste the output of running job

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. CentOS]
 - JDK Version [e.g. 1.8]
 - DataX Version [e.g. 3.2.3]

**Additional context**
当httpreader插件返回结果里面的字段值是null时候，出错，出错信息：ERROR Engine - ILLEGAL_VALUE - ILLEGAL_VALUE - 您尝试从结果中获取key为 'HZSRM3'的结果，但实际结果中不存在该key值

json:
        {
            "HZSRM3": null,
            "XGCZSJ": "2015-09-08 14:00:33",
        },

**Comment by meihuasannong** [comment]
@wgzhao

**Comment by wgzhao** [comment]
感谢你的反馈
请给出完整的json文件以及执行时的完整输出

**Comment by meihuasannong** [comment]
> 感谢你的反馈
> 请给出完整的json文件以及执行时的完整输出
以下是完成job文件，
{
  "job": {
    "setting": {
      "speed": {
        "channel": 1,
        "bytes": -1
      }
    },
    "content": [
      {
        "reader": {
          "name": "httpreader",
          "parameter": {
          	"nullFormat": "",
            "connection": [
              {
                "url": "http://127.0.0.1/API/internal/synchronous/get",
              }
            ],
            "reqParams": {
              "nextId":"${maxid}",
              "where":"${limit}",
              "token":"ssss"
            },
            "resultKey":"result",
            "method": "GET",
            "encoding": "utf-8",
            "column": [
  
                        "XGCZSJ",
                        "HZSRM3",
       
            ],
            // "username": "user",
            // "password": "passw0rd",
            "headers": {
                "X-Access-Token": ""
            }
          }
        },
        "writer": {
          "name": "streamwriter",
          "parameter": {
            "print": "true"
          }
        }
      }
    ]
  }
}

其中http返回值格式如下：
{
    "success": true,
    "message": "操作成功！",
    "code": 200,
    "result": [
        {
            "HZSRM3": null,
            "XGCZSJ": "2015-09-08 14:00:33",
        },
        {
            "HZSRM3": null,
            "XGCZSJ": "2015-09-08 14:00:33",
        }
    ]

完整日志：

2021-05-28 04:32:03.293 [main] INFO  PerfTrace - PerfTrace traceId=job_-1, isEnable=false, priority=0
2021-05-28 04:32:03.293 [main] INFO  JobContainer - DataX jobContainer starts job.
2021-05-28 04:32:03.298 [main] INFO  JobContainer - Set jobId = 0
2021-05-28 04:32:03.370 [job-0] INFO  JobContainer - DataX Reader.Job [httpreader] do prepare work .
2021-05-28 04:32:03.372 [job-0] INFO  JobContainer - DataX Writer.Job [streamwriter] do prepare work .
2021-05-28 04:32:03.372 [job-0] INFO  JobContainer - Job set Channel-Number to 1 channels.
2021-05-28 04:32:03.373 [job-0] INFO  JobContainer - DataX Reader.Job [httpreader] splits to [1] tasks.
2021-05-28 04:32:03.374 [job-0] INFO  JobContainer - DataX Writer.Job [streamwriter] splits to [1] tasks.
2021-05-28 04:32:03.414 [job-0] INFO  JobContainer - Scheduler starts [1] taskGroups.
2021-05-28 04:32:03.433 [taskGroup-0] INFO  TaskGroupContainer - taskGroupId=[0] start [1] channels for [1] tasks.
2021-05-28 04:32:03.452 [taskGroup-0] INFO  Channel - Channel set byte_speed_limit to -1, No bps activated.
2021-05-28 04:32:03.453 [taskGroup-0] INFO  Channel - Channel set record_speed_limit to -1, No tps activated.
2021-05-28 04:32:04.210 [0-0-0-reader] ERROR ReaderRunner - Reader runner Received Exceptions:
com.wgzhao.datax.common.exception.DataXException: ILLEGAL_VALUE - 您尝试从结果中获取key为 'HZSRM3'的结果，但实际结果中不存在该key值
	at com.wgzhao.datax.common.exception.DataXException.asDataXException(DataXException.java:50)
	at com.wgzhao.datax.plugin.reader.httpreader.HttpReader$Task.startRead(HttpReader.java:200)
	at com.wgzhao.datax.core.taskgroup.runner.ReaderRunner.run(ReaderRunner.java:82)
	at java.lang.Thread.run(Thread.java:748)
2021-05-28 04:32:06.457 [job-0] ERROR JobContainer - 运行scheduler出错.
2021-05-28 04:32:06.459 [job-0] INFO  StandAloneJobContainerCommunicator - Total 0 records, 0 bytes | Speed 0B/s, 0 records/s | Error 0 records, 0 bytes |  All Task WaitWriterTime 0.000s |  All Task WaitReaderTime 0.000s | Percentage 0.00%
2021-05-28 04:32:06.460 [job-0] ERROR Engine - ILLEGAL_VALUE - ILLEGAL_VALUE - 您尝试从结果中获取key为 'HZSRM3'的结果，但实际结果中不存在该key值

**Comment by wgzhao** [comment]
问题的原因是 `fastjson` 包在分析json串时，对值为空的key直接过滤了

**Comment by wgzhao** [comment]
已经修复，你可以尝试用下面的附件[httpreader-3.2.5-SNAPSHOT.zip](https://github.com/wgzhao/DataX/files/6567536/httpreader-3.2.5-SNAPSHOT.zip)进行临时修复，步骤如下：

1. 下载上述附件到临时目录，假定是 `/tmp/httpreader-3.2.5-SNAPSHOT.zip`
2. 切换到 DataX 主目录（包含 `bin` 子目录的那级目录），假定是 `/opt/datax`
3. 删除原来的插件 `rm -rf plugin/reader/httpreader`
4. 安装新的插件 `unzip /tmp/httpreader-3.2.5-SNAPSHOT.zip`
5. 测试

**Comment by meihuasannong** [comment]
> 已经修复，你可以尝试用下面的附件[httpreader-3.2.5-SNAPSHOT.zip](https://github.com/wgzhao/DataX/files/6567536/httpreader-3.2.5-SNAPSHOT.zip)进行临时修复，步骤如下：
> 
> 1. 下载上述附件到临时目录，假定是 `/tmp/httpreader-3.2.5-SNAPSHOT.zip`
> 2. 切换到 DataX 主目录（包含 `bin` 子目录的那级目录），假定是 `/opt/datax`
> 3. 删除原来的插件 `rm -rf plugin/reader/httpreader`
> 4. 安装新的插件 `unzip /tmp/httpreader-3.2.5-SNAPSHOT.zip`
> 5. 测试



> 已经修复，你可以尝试用下面的附件[httpreader-3.2.5-SNAPSHOT.zip](https://github.com/wgzhao/DataX/files/6567536/httpreader-3.2.5-SNAPSHOT.zip)进行临时修复，步骤如下：
> 
> 1. 下载上述附件到临时目录，假定是 `/tmp/httpreader-3.2.5-SNAPSHOT.zip`
> 2. 切换到 DataX 主目录（包含 `bin` 子目录的那级目录），假定是 `/opt/datax`
> 3. 删除原来的插件 `rm -rf plugin/reader/httpreader`
> 4. 安装新的插件 `unzip /tmp/httpreader-3.2.5-SNAPSHOT.zip`
> 5. 测试

感谢！！，已经可以了
