### ISSUE TITLE
写入的目标表中含有保留字时报错

### ISSUE THREAD

**Issue by wgzhao** [wgzhao/DataX#59]
以写入MySQL为例，以下是任务文件

```json
{
    "job": {
        "setting": {
            "speed": {
                "channel": 3
            }
        },
        "content": [
            {
                "writer": {
                    "name": "mysqlwriter",
                    "parameter": {
                        "username": "root",
                        "password": "123456",
                        "column": [
                            "id", "date","table"
                        ],
                        "connection": [
                            {
                                "table": [
                                    "tbl_test"
                                ],
                                "jdbcUrl": "jdbc:mysql://127.0.0.1:3306/test"
                            }
                        ]
                    }
                },
                "reader": {
                    "name": "streamreader",
                    "parameter": {
                        "column": [
                            {
                                "value": "123",
                                "type": "long"
                            },
			  {"value":"2020-11-12", "type":"string"},
			{"value":"hello", "type":"string"}
                        ],
                        "sliceRecordCount": 10
                    }
                }
            }
        ]
    }
}
```

执行时报错如下：

```
....
020-11-16 20:25:48.028 [job-0] ERROR JobContainer - Exception when job run
com.alibaba.datax.common.exception.DataXException: Code:[DBUtilErrorCode-01], Description:[获取表字段相关信息失败.].  - 获取表:tbl_test 的字段的元信息时失败. 请联系 DBA 核查该库、表信息. - java.sql.SQLSyntaxErrorException: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'table from tbl_test where 1=2' at line 1
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:120)
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:97)
	at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:122)
	at com.mysql.cj.jdbc.StatementImpl.executeQuery(StatementImpl.java:1200)
	at com.alibaba.datax.plugin.rdbms.util.DBUtil.getColumnMetaData(DBUtil.java:542)
	at com.alibaba.datax.plugin.rdbms.writer.util.OriginalConfPretreatmentUtil.dealColumnConf(OriginalConfPretreatmentUtil.java:133)
	at com.alibaba.datax.plugin.rdbms.writer.util.OriginalConfPretreatmentUtil.dealColumnConf(OriginalConfPretreatmentUtil.java:148)
	at com.alibaba.datax.plugin.rdbms.writer.util.OriginalConfPretreatmentUtil.doPretreatment(OriginalConfPretreatmentUtil.java:43)
	at com.alibaba.datax.plugin.rdbms.writer.CommonRdbmsWriter$Job.init(CommonRdbmsWriter.java:41)
	at com.alibaba.datax.plugin.writer.mysqlwriter.MysqlWriter$Job.init(MysqlWriter.java:30)
	at com.alibaba.datax.core.job.JobContainer.initJobWriter(JobContainer.java:687)
	at com.alibaba.datax.core.job.JobContainer.init(JobContainer.java:313)
	at com.alibaba.datax.core.job.JobContainer.start(JobContainer.java:124)
	at com.alibaba.datax.core.Engine.start(Engine.java:88)
	at com.alibaba.datax.core.Engine.entry(Engine.java:149)
	at com.alibaba.datax.core.Engine.main(Engine.java:164)

	at com.alibaba.datax.common.exception.DataXException.asDataXException(DataXException.java:33)
	at com.alibaba.datax.plugin.rdbms.util.DBUtil.getColumnMetaData(DBUtil.java:555)
	at com.alibaba.datax.plugin.rdbms.writer.util.OriginalConfPretreatmentUtil.dealColumnConf(OriginalConfPretreatmentUtil.java:133)
	at com.alibaba.datax.plugin.rdbms.writer.util.OriginalConfPretreatmentUtil.dealColumnConf(OriginalConfPretreatmentUtil.java:148)
	at com.alibaba.datax.plugin.rdbms.writer.util.OriginalConfPretreatmentUtil.doPretreatment(OriginalConfPretreatmentUtil.java:43)
	at com.alibaba.datax.plugin.rdbms.writer.CommonRdbmsWriter$Job.init(CommonRdbmsWriter.java:41)
	at com.alibaba.datax.plugin.writer.mysqlwriter.MysqlWriter$Job.init(MysqlWriter.java:30)
	at com.alibaba.datax.core.job.JobContainer.initJobWriter(JobContainer.java:687)
	at com.alibaba.datax.core.job.JobContainer.init(JobContainer.java:313)
	at com.alibaba.datax.core.job.JobContainer.start(JobContainer.java:124)
	at com.alibaba.datax.core.Engine.start(Engine.java:88)
	at com.alibaba.datax.core.Engine.entry(Engine.java:149)
	at com.alibaba.datax.core.Engine.main(Engine.java:164)
Caused by: java.sql.SQLSyntaxErrorException: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'table from tbl_test where 1=2' at line 1
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:120)
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:97)
	at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:122)
	at com.mysql.cj.jdbc.StatementImpl.executeQuery(StatementImpl.java:1200)
	at com.alibaba.datax.plugin.rdbms.util.DBUtil.getColumnMetaData(DBUtil.java:542)
	... 11 common frames omitted
````

**Comment by wgzhao** [comment]
虽然可以在处理字段时自动加上引号来实现，但更通用的做法是在在json文件里直接把这些保留字或关键字用引号标记，比如这样：

```json
{
    "job": {
        "setting": {
            "speed": {
                "channel": 3
            }
        },
        "content": [
            {
                "writer": {
                    "name": "mysqlwriter",
                    "parameter": {
                        "username": "root",
                        "password": "123456",
                        "column": [
                            "id", "`date`","`table`"
                        ],
                        "connection": [
                            {
                                "table": [
                                    "tbl_test"
                                ],
                                "jdbcUrl": "jdbc:mysql://127.0.0.1:3306/test"
                            }
                        ]
                    }
                },
                "reader": {
                    "name": "streamreader",
                    "parameter": {
                        "column": [
                            {
                                "value": "123",
                                "type": "long"
                            },
			  {"value":"2020-11-12", "type":"string"},
			{"value":"hello", "type":"string"}
                        ],
                        "sliceRecordCount": 10
                    }
                }
            }
        ]
    }
}
```
